name: pkgcheck

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.xml'
      - 'Manifest'
      - '.cz'
      - '.gitignore'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.xml'
      - 'Manifest'
      - '.cz'
      - '.gitignore'
  schedule:
    - cron: '4 6 * * 6'

permissions:
  contents: read

jobs:
  pkgcheck:
    name: pkgcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          since_last_remote_commit: true
          files: |
            **/*.ebuild
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.7
        with:
          since_last_remote_commit: true
          files: |
            app-admin/awsls/*.ebuild
            app-admin/sinker/*.ebuild
            app-admin/sops/*.ebuild
            app-admin/terraform-provider-vcd/*.ebuild
            app-backup/clickhouse-backup/*.ebuild
            app-backup/wal-g/*.ebuild
            dev-db/litestream/*.ebuild
            dev-db/usql/*.ebuild
            dev-util/act/*.ebuild
            dev-vcs/gitaly/*.ebuild
            app-metrics/amazon-cloudwatch-agent/*.ebuild
            app-metrics/aws-otel-collector/*.ebuild
            app-misc/fq/*.ebuild
            app-misc/gron/*.ebuild
            app-misc/pet/*.ebuild
            dev-util/packer/*.ebuild
            dev-util/tickgit/*.ebuild
            net-analyzer/sx/*.ebuild
            net-misc/curlie/*.ebuild
            net-misc/wuzz/*.ebuild
            www-servers/gitlab-workhorse/*.ebuild
      - name: Define pkgcheck args
        uses: haya14busa/action-cond@v1
        id: condition
        with:
          cond: ${{ steps.changed-files-specific.outputs.any_changed == 'true' }}
          if_true: "--keywords=-RedundantVersion"
          if_false: "--net --user-agent 'Mozilla/5.0' --timeout 15 --keywords=-RedundantVersion"
      - name: Run pkgcheck
        uses: pkgcore/pkgcheck-action@v1
        with:
          args: ${{ steps.condition.outputs.value }} ${{ steps.changed-files.outputs.all_changed_files }}
          pkgs: pkgcheck>=0.10.3 requests
