name: sasts

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '4 3 * * 6'

permissions:
  contents: read

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Run gitleaks
        uses: zricethezav/gitleaks-action@master
  whispers:
    name: whispers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup python
        uses: actions/checkout@v3
      - name: Run whisper
        run: |
          pip install whispers
          whispers -c .github/whispers.yml
