name: shellcheck

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -s bash -e SC2034 -e SC2016 -e SC2191 -e SC2037
      with:
        additional_files: '*.ebuild'
        ignore_names: '*.bash *.zsh'
